<?php
	$dbServer = 'localhost';
	$dbUsername = 'root';
	$dbPassword = '';
	$dbDatabase = 'tenant_tih_db';
	$dbPort = '3306';
	$appURI = 'tenet-iittnif-apps';
	$host = '127.0.0.1';

	$adminConfig = [
		'adminUsername' => "admin",
		'adminPassword' => "\$2y\$10\$7MNt0ZAXKwo1rLRVavZNueKJNoPWBLL1V3PLT5XsS4nw1mvM13PYq",
		'senderEmail' => "sanjay@iittnif.com",
		'notifyAdminNewMembers' => "",
		'defaultSignUp' => "1",
		'anonymousGroup' => "anonymous",
		'anonymousMember' => "guest",
		'groupsPerPage' => "10",
		'membersPerPage' => "10",
		'recordsPerPage' => "10",
		'custom1' => "Full Name",
		'custom2' => "Address",
		'custom3' => "City",
		'custom4' => "State",
		'custom5' => "Tenant ID",
		'MySQLDateFormat' => "%d/%m/%Y",
		'PHPDateFormat' => "j/n/Y",
		'PHPDateTimeFormat' => "d/m/Y, h:i a",
		'senderName' => "Membership management",
		'approvalSubject' => "Your membership is now approved",
		'approvalMessage' => "Dear member,\n\nYour membership is now approved by the admin. You can log in to your account here:\nhttp://127.0.0.1/tenet-iittnif-apps\n\nRegards,\nAdmin",
		'hide_twitter_feed' => "",
		'maintenance_mode_message' => "<b>Our website is currently down for maintenance</b><br>\r\nWe expect to be back in a couple hours. Thanks for your patience.",
		'mail_function' => "mail",
		'smtp_server' => "",
		'smtp_encryption' => "",
		'smtp_port' => "25",
		'smtp_user' => "",
		'smtp_pass' => "",
		'googleAPIKey' => "",
		'baseUploadPath' => "images",
	];