<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/event_table.php');
	include_once(__DIR__ . '/event_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('event_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'event_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`event_table`.`id`" => "id",
		"`event_table`.`event_name`" => "event_name",
		"`event_table`.`participants`" => "participants",
		"`event_table`.`venue`" => "venue",
		"if(`event_table`.`event_from_date`,date_format(`event_table`.`event_from_date`,'%d/%m/%Y'),'')" => "event_from_date",
		"if(`event_table`.`event_to_date`,date_format(`event_table`.`event_to_date`,'%d/%m/%Y'),'')" => "event_to_date",
		"`event_table`.`created_by`" => "created_by",
		"`event_table`.`created_at`" => "created_at",
		"`event_table`.`last_updated_by`" => "last_updated_by",
		"`event_table`.`last_updated_at`" => "last_updated_at",
		"`event_table`.`tenant_id`" => "tenant_id",
		"`event_table`.`event_str`" => "event_str",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`event_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`event_table`.`event_from_date`',
		6 => '`event_table`.`event_to_date`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`event_table`.`tenant_id`',
		12 => 12,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`event_table`.`id`" => "id",
		"`event_table`.`event_name`" => "event_name",
		"`event_table`.`participants`" => "participants",
		"`event_table`.`venue`" => "venue",
		"if(`event_table`.`event_from_date`,date_format(`event_table`.`event_from_date`,'%d/%m/%Y'),'')" => "event_from_date",
		"if(`event_table`.`event_to_date`,date_format(`event_table`.`event_to_date`,'%d/%m/%Y'),'')" => "event_to_date",
		"`event_table`.`created_by`" => "created_by",
		"`event_table`.`created_at`" => "created_at",
		"`event_table`.`last_updated_by`" => "last_updated_by",
		"`event_table`.`last_updated_at`" => "last_updated_at",
		"`event_table`.`tenant_id`" => "tenant_id",
		"`event_table`.`event_str`" => "event_str",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`event_table`.`id`" => "ID",
		"`event_table`.`event_name`" => "Event name",
		"`event_table`.`participants`" => "Participants",
		"`event_table`.`venue`" => "Venue",
		"`event_table`.`event_from_date`" => "Event from date",
		"`event_table`.`event_to_date`" => "Event to date",
		"`event_table`.`created_by`" => "Created by",
		"`event_table`.`created_at`" => "Created at",
		"`event_table`.`last_updated_by`" => "Last updated by",
		"`event_table`.`last_updated_at`" => "Last updated at",
		"`event_table`.`tenant_id`" => "Tenant ID",
		"`event_table`.`event_str`" => "Event str",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`event_table`.`id`" => "id",
		"`event_table`.`event_name`" => "event_name",
		"`event_table`.`participants`" => "participants",
		"`event_table`.`venue`" => "venue",
		"if(`event_table`.`event_from_date`,date_format(`event_table`.`event_from_date`,'%d/%m/%Y'),'')" => "event_from_date",
		"if(`event_table`.`event_to_date`,date_format(`event_table`.`event_to_date`,'%d/%m/%Y'),'')" => "event_to_date",
		"`event_table`.`created_by`" => "created_by",
		"`event_table`.`created_at`" => "created_at",
		"`event_table`.`last_updated_by`" => "last_updated_by",
		"`event_table`.`last_updated_at`" => "last_updated_at",
		"`event_table`.`tenant_id`" => "tenant_id",
		"`event_table`.`event_str`" => "event_str",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`event_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'event_table_view.php';
	$x->TableTitle = 'Event - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`event_table`.`id`';
	$x->DefaultSortField = '`event_table`.`event_from_date`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Event name', 'Participants', 'Venue', 'Event from date', 'Event to date', 'Created by', 'Created at', 'Last updated by', 'Last updated at', 'Event str', ];
	$x->ColFieldName = ['id', 'event_name', 'participants', 'venue', 'event_from_date', 'event_to_date', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', 'event_str', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/event_table_templateTV.html';
	$x->SelectedTemplate = 'templates/event_table_templateTVS.html';
	$x->TemplateDV = 'templates/event_table_templateDV.html';
	$x->TemplateDVP = 'templates/event_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: event_table_init
	$render = true;
	if(function_exists('event_table_init')) {
		$args = [];
		$render = event_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: event_table_header
	$headerCode = '';
	if(function_exists('event_table_header')) {
		$args = [];
		$headerCode = event_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: event_table_footer
	$footerCode = '';
	if(function_exists('event_table_footer')) {
		$args = [];
		$footerCode = event_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
