<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/event_decision_table.php');
	include_once(__DIR__ . '/event_decision_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('event_decision_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'event_decision_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`event_decision_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`event_outcomes_expected_table1`.`outcomes_expected_str`), CONCAT_WS('',   `event_outcomes_expected_table1`.`outcomes_expected_str`), '') /* Expected Outcomes of Meeting */" => "outcomes_expected_lookup",
		"`event_decision_table`.`decision_description`" => "decision_description",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Decision actor */" => "decision_actor",
		"if(`event_decision_table`.`action_taken_with_date`,date_format(`event_decision_table`.`action_taken_with_date`,'%d/%m/%Y'),'')" => "action_taken_with_date",
		"`event_decision_table`.`decision_status`" => "decision_status",
		"if(`event_decision_table`.`decision_status_update_date`,date_format(`event_decision_table`.`decision_status_update_date`,'%d/%m/%Y'),'')" => "decision_status_update_date",
		"`event_decision_table`.`decision_status_remarks_by_superior`" => "decision_status_remarks_by_superior",
		"`event_decision_table`.`created_by`" => "created_by",
		"`event_decision_table`.`created_at`" => "created_at",
		"`event_decision_table`.`last_updated_by`" => "last_updated_by",
		"`event_decision_table`.`last_updated_at`" => "last_updated_at",
		"`event_decision_table`.`tenant_id`" => "tenant_id",
		"`event_decision_table`.`event_decision_str`" => "event_decision_str",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`event_decision_table`.`id`',
		2 => '`event_outcomes_expected_table1`.`outcomes_expected_str`',
		3 => 3,
		4 => 4,
		5 => '`event_decision_table`.`action_taken_with_date`',
		6 => 6,
		7 => '`event_decision_table`.`decision_status_update_date`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => '`event_decision_table`.`tenant_id`',
		14 => 14,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`event_decision_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`event_outcomes_expected_table1`.`outcomes_expected_str`), CONCAT_WS('',   `event_outcomes_expected_table1`.`outcomes_expected_str`), '') /* Expected Outcomes of Meeting */" => "outcomes_expected_lookup",
		"`event_decision_table`.`decision_description`" => "decision_description",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Decision actor */" => "decision_actor",
		"if(`event_decision_table`.`action_taken_with_date`,date_format(`event_decision_table`.`action_taken_with_date`,'%d/%m/%Y'),'')" => "action_taken_with_date",
		"`event_decision_table`.`decision_status`" => "decision_status",
		"if(`event_decision_table`.`decision_status_update_date`,date_format(`event_decision_table`.`decision_status_update_date`,'%d/%m/%Y'),'')" => "decision_status_update_date",
		"`event_decision_table`.`decision_status_remarks_by_superior`" => "decision_status_remarks_by_superior",
		"`event_decision_table`.`created_by`" => "created_by",
		"`event_decision_table`.`created_at`" => "created_at",
		"`event_decision_table`.`last_updated_by`" => "last_updated_by",
		"`event_decision_table`.`last_updated_at`" => "last_updated_at",
		"`event_decision_table`.`tenant_id`" => "tenant_id",
		"`event_decision_table`.`event_decision_str`" => "event_decision_str",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`event_decision_table`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`event_outcomes_expected_table1`.`outcomes_expected_str`), CONCAT_WS('',   `event_outcomes_expected_table1`.`outcomes_expected_str`), '') /* Expected Outcomes of Meeting */" => "Expected Outcomes of Meeting",
		"`event_decision_table`.`decision_description`" => "Decision description",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Decision actor */" => "Decision actor",
		"`event_decision_table`.`action_taken_with_date`" => "Action taken with date",
		"`event_decision_table`.`decision_status`" => "Decision status",
		"`event_decision_table`.`decision_status_update_date`" => "Decision status update date",
		"`event_decision_table`.`decision_status_remarks_by_superior`" => "Decision status remarks by superior",
		"`event_decision_table`.`created_by`" => "Created by",
		"`event_decision_table`.`created_at`" => "Created at",
		"`event_decision_table`.`last_updated_by`" => "Last updated by",
		"`event_decision_table`.`last_updated_at`" => "Last updated at",
		"`event_decision_table`.`tenant_id`" => "Tenant ID",
		"`event_decision_table`.`event_decision_str`" => "Event decision str",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`event_decision_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`event_outcomes_expected_table1`.`outcomes_expected_str`), CONCAT_WS('',   `event_outcomes_expected_table1`.`outcomes_expected_str`), '') /* Expected Outcomes of Meeting */" => "outcomes_expected_lookup",
		"`event_decision_table`.`decision_description`" => "decision_description",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Decision actor */" => "decision_actor",
		"if(`event_decision_table`.`action_taken_with_date`,date_format(`event_decision_table`.`action_taken_with_date`,'%d/%m/%Y'),'')" => "action_taken_with_date",
		"`event_decision_table`.`decision_status`" => "decision_status",
		"if(`event_decision_table`.`decision_status_update_date`,date_format(`event_decision_table`.`decision_status_update_date`,'%d/%m/%Y'),'')" => "decision_status_update_date",
		"`event_decision_table`.`decision_status_remarks_by_superior`" => "decision_status_remarks_by_superior",
		"`event_decision_table`.`created_by`" => "created_by",
		"`event_decision_table`.`created_at`" => "created_at",
		"`event_decision_table`.`last_updated_by`" => "last_updated_by",
		"`event_decision_table`.`last_updated_at`" => "last_updated_at",
		"`event_decision_table`.`tenant_id`" => "tenant_id",
		"`event_decision_table`.`event_decision_str`" => "event_decision_str",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['outcomes_expected_lookup' => 'Expected Outcomes of Meeting', 'decision_actor' => 'Decision actor', ];

	$x->QueryFrom = "`event_decision_table` LEFT JOIN `event_outcomes_expected_table` as event_outcomes_expected_table1 ON `event_outcomes_expected_table1`.`id`=`event_decision_table`.`outcomes_expected_lookup` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`id`=`event_decision_table`.`decision_actor` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'event_decision_table_view.php';
	$x->TableTitle = 'Decision - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`event_decision_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Expected Outcomes of Meeting', 'Decision description', 'Decision actor', 'Action taken with date', 'Decision status', 'Decision status update date', 'Decision status remarks by superior', 'Created by', 'Created at', 'Last updated by', 'Last updated at', 'Tenant ID', 'Event decision str', ];
	$x->ColFieldName = ['id', 'outcomes_expected_lookup', 'decision_description', 'decision_actor', 'action_taken_with_date', 'decision_status', 'decision_status_update_date', 'decision_status_remarks_by_superior', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', 'tenant_id', 'event_decision_str', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/event_decision_table_templateTV.html';
	$x->SelectedTemplate = 'templates/event_decision_table_templateTVS.html';
	$x->TemplateDV = 'templates/event_decision_table_templateDV.html';
	$x->TemplateDVP = 'templates/event_decision_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: event_decision_table_init
	$render = true;
	if(function_exists('event_decision_table_init')) {
		$args = [];
		$render = event_decision_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: event_decision_table_header
	$headerCode = '';
	if(function_exists('event_decision_table_header')) {
		$args = [];
		$headerCode = event_decision_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: event_decision_table_footer
	$footerCode = '';
	if(function_exists('event_decision_table_footer')) {
		$args = [];
		$footerCode = event_decision_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
