<?php

// Data functions (insert, update, delete, form) for table meetings_decision_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function meetings_decision_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('meetings_decision_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	// automatic agenda_lookup if passed as filterer
	if(Request::val('filterer_agenda_lookup')) {
		$_REQUEST['agenda_lookup'] = Request::val('filterer_agenda_lookup');
	}

	$data = [
		'decision_description' => br2nl(Request::val('decision_description', '')),
		'decision_actor' => Request::lookup('decision_actor', ''),
		'action_taken_with_date' => Request::dateComponents('action_taken_with_date', ''),
		'decision_status' => Request::val('decision_status', 'Yet to Start'),
		'decision_status_update_date' => Request::dateComponents('decision_status_update_date', ''),
		'decision_status_remarks_by_superior' => Request::val('decision_status_remarks_by_superior', ''),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];


	// automatic agenda_lookup if passed as filterer
	if(Request::val('filterer_agenda_lookup')) {
		$data['agenda_lookup'] = Request::val('filterer_agenda_lookup');
	}
	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('meetings_decision_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		meetings_decision_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function meetings_decision_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function meetings_decision_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('meetings_decision_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: meetings_decision_table_before_delete
	if(function_exists('meetings_decision_table_before_delete')) {
		$args = [];
		if(!meetings_decision_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `meetings_decision_table` WHERE `id`='{$selected_id}'", $eo);

	// hook: meetings_decision_table_after_delete
	if(function_exists('meetings_decision_table_after_delete')) {
		$args = [];
		meetings_decision_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='meetings_decision_table' AND `pkValue`='{$selected_id}'", $eo);
}

function meetings_decision_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('meetings_decision_table', $selected_id, 'edit')) return false;

	$data = [
		'decision_description' => br2nl(Request::val('decision_description', '')),
		'decision_actor' => Request::lookup('decision_actor', ''),
		'action_taken_with_date' => Request::dateComponents('action_taken_with_date', ''),
		'decision_status' => Request::val('decision_status', ''),
		'decision_status_update_date' => Request::dateComponents('decision_status_update_date', ''),
		'decision_status_remarks_by_superior' => Request::val('decision_status_remarks_by_superior', ''),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('meetings_decision_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: meetings_decision_table_before_update
	if(function_exists('meetings_decision_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!meetings_decision_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'meetings_decision_table', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="meetings_decision_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('meetings_decision_table', $data['selectedID'], calculated_fields()['meetings_decision_table']);

	// hook: meetings_decision_table_after_update
	if(function_exists('meetings_decision_table_after_update')) {
		if($row = getRecord('meetings_decision_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!meetings_decision_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('meetings_decision_table', $selected_id);
}

function meetings_decision_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('meetings_decision_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('meetings_decision_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('meetings_decision_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('meetings_decision_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_agenda_lookup = Request::val('filterer_agenda_lookup');
	$filterer_decision_actor = Request::val('filterer_decision_actor');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: agenda_lookup
	$combo_agenda_lookup = new DataCombo;
	// combobox: decision_actor
	$combo_decision_actor = new DataCombo;
	// combobox: action_taken_with_date
	$combo_action_taken_with_date = new DateCombo;
	$combo_action_taken_with_date->DateFormat = "dmy";
	$combo_action_taken_with_date->MinYear = defined('meetings_decision_table.action_taken_with_date.MinYear') ? constant('meetings_decision_table.action_taken_with_date.MinYear') : 1900;
	$combo_action_taken_with_date->MaxYear = defined('meetings_decision_table.action_taken_with_date.MaxYear') ? constant('meetings_decision_table.action_taken_with_date.MaxYear') : 2100;
	$combo_action_taken_with_date->DefaultDate = parseMySQLDate('', '');
	$combo_action_taken_with_date->MonthNames = $Translation['month names'];
	$combo_action_taken_with_date->NamePrefix = 'action_taken_with_date';
	// combobox: decision_status
	$combo_decision_status = new Combo;
	$combo_decision_status->ListType = 0;
	$combo_decision_status->MultipleSeparator = ', ';
	$combo_decision_status->ListBoxHeight = 10;
	$combo_decision_status->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/meetings_decision_table.decision_status.csv')) {
		$decision_status_data = addslashes(implode('', @file(__DIR__ . '/hooks/meetings_decision_table.decision_status.csv')));
		$combo_decision_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($decision_status_data))));
		$combo_decision_status->ListData = $combo_decision_status->ListItem;
	} else {
		$combo_decision_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Completed;;On-going;;Yet to Start"))));
		$combo_decision_status->ListData = $combo_decision_status->ListItem;
	}
	$combo_decision_status->SelectName = 'decision_status';
	// combobox: decision_status_update_date
	$combo_decision_status_update_date = new DateCombo;
	$combo_decision_status_update_date->DateFormat = "dmy";
	$combo_decision_status_update_date->MinYear = defined('meetings_decision_table.decision_status_update_date.MinYear') ? constant('meetings_decision_table.decision_status_update_date.MinYear') : 1900;
	$combo_decision_status_update_date->MaxYear = defined('meetings_decision_table.decision_status_update_date.MaxYear') ? constant('meetings_decision_table.decision_status_update_date.MaxYear') : 2100;
	$combo_decision_status_update_date->DefaultDate = parseMySQLDate('', '');
	$combo_decision_status_update_date->MonthNames = $Translation['month names'];
	$combo_decision_status_update_date->NamePrefix = 'decision_status_update_date';

	if($hasSelectedId) {
		if(!($row = getRecord('meetings_decision_table', $selectedId))) {
			return error_message($Translation['No records found'], 'meetings_decision_table_view.php', false);
		}
		$combo_agenda_lookup->SelectedData = $row['agenda_lookup'];
		$combo_decision_actor->SelectedData = $row['decision_actor'];
		$combo_action_taken_with_date->DefaultDate = $row['action_taken_with_date'];
		$combo_decision_status->SelectedData = $row['decision_status'];
		$combo_decision_status_update_date->DefaultDate = $row['decision_status_update_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_agenda_lookup->SelectedData = $filterer_agenda_lookup;
		$combo_decision_actor->SelectedData = $filterer_decision_actor;
		$combo_decision_status->SelectedText = (isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8('Yet to Start'));
	}
	$combo_agenda_lookup->HTML = '<span id="agenda_lookup-container' . $rnd1 . '"></span><input type="hidden" name="agenda_lookup" id="agenda_lookup' . $rnd1 . '" value="' . html_attr($combo_agenda_lookup->SelectedData) . '">';
	$combo_agenda_lookup->MatchText = '<span id="agenda_lookup-container-readonly' . $rnd1 . '"></span><input type="hidden" name="agenda_lookup" id="agenda_lookup' . $rnd1 . '" value="' . html_attr($combo_agenda_lookup->SelectedData) . '">';
	$combo_decision_actor->HTML = '<span id="decision_actor-container' . $rnd1 . '"></span><input type="hidden" name="decision_actor" id="decision_actor' . $rnd1 . '" value="' . html_attr($combo_decision_actor->SelectedData) . '">';
	$combo_decision_actor->MatchText = '<span id="decision_actor-container-readonly' . $rnd1 . '"></span><input type="hidden" name="decision_actor" id="decision_actor' . $rnd1 . '" value="' . html_attr($combo_decision_actor->SelectedData) . '">';
	$combo_decision_status->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_agenda_lookup__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['agenda_lookup'] : htmlspecialchars($filterer_agenda_lookup, ENT_QUOTES)); ?>"};
		AppGini.current_decision_actor__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['decision_actor'] : htmlspecialchars($filterer_decision_actor, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(agenda_lookup_reload__RAND__) == 'function') agenda_lookup_reload__RAND__();
				if(typeof(decision_actor_reload__RAND__) == 'function') decision_actor_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function agenda_lookup_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#agenda_lookup-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_agenda_lookup__RAND__.value, t: 'meetings_decision_table', f: 'agenda_lookup' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="agenda_lookup"]').val(resp.results[0].id);
							$j('[id=agenda_lookup-container-readonly__RAND__]').html('<span class="match-text" id="agenda_lookup-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=meetings_agenda_table_view_parent]').hide(); } else { $j('.btn[id=meetings_agenda_table_view_parent]').show(); }


							if(typeof(agenda_lookup_update_autofills__RAND__) == 'function') agenda_lookup_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'meetings_decision_table', f: 'agenda_lookup' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_agenda_lookup__RAND__.value = e.added.id;
				AppGini.current_agenda_lookup__RAND__.text = e.added.text;
				$j('[name="agenda_lookup"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=meetings_agenda_table_view_parent]').hide(); } else { $j('.btn[id=meetings_agenda_table_view_parent]').show(); }


				if(typeof(agenda_lookup_update_autofills__RAND__) == 'function') agenda_lookup_update_autofills__RAND__();
			});

			if(!$j("#agenda_lookup-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_agenda_lookup__RAND__.value, t: 'meetings_decision_table', f: 'agenda_lookup' },
					success: function(resp) {
						$j('[name="agenda_lookup"]').val(resp.results[0].id);
						$j('[id=agenda_lookup-container-readonly__RAND__]').html('<span class="match-text" id="agenda_lookup-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=meetings_agenda_table_view_parent]').hide(); } else { $j('.btn[id=meetings_agenda_table_view_parent]').show(); }

						if(typeof(agenda_lookup_update_autofills__RAND__) == 'function') agenda_lookup_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_agenda_lookup__RAND__.value, t: 'meetings_decision_table', f: 'agenda_lookup' },
				success: function(resp) {
					$j('[id=agenda_lookup-container__RAND__], [id=agenda_lookup-container-readonly__RAND__]').html('<span class="match-text" id="agenda_lookup-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=meetings_agenda_table_view_parent]').hide(); } else { $j('.btn[id=meetings_agenda_table_view_parent]').show(); }

					if(typeof(agenda_lookup_update_autofills__RAND__) == 'function') agenda_lookup_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function decision_actor_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#decision_actor-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_decision_actor__RAND__.value, t: 'meetings_decision_table', f: 'decision_actor' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="decision_actor"]').val(resp.results[0].id);
							$j('[id=decision_actor-container-readonly__RAND__]').html('<span class="match-text" id="decision_actor-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


							if(typeof(decision_actor_update_autofills__RAND__) == 'function') decision_actor_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'meetings_decision_table', f: 'decision_actor' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_decision_actor__RAND__.value = e.added.id;
				AppGini.current_decision_actor__RAND__.text = e.added.text;
				$j('[name="decision_actor"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


				if(typeof(decision_actor_update_autofills__RAND__) == 'function') decision_actor_update_autofills__RAND__();
			});

			if(!$j("#decision_actor-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_decision_actor__RAND__.value, t: 'meetings_decision_table', f: 'decision_actor' },
					success: function(resp) {
						$j('[name="decision_actor"]').val(resp.results[0].id);
						$j('[id=decision_actor-container-readonly__RAND__]').html('<span class="match-text" id="decision_actor-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

						if(typeof(decision_actor_update_autofills__RAND__) == 'function') decision_actor_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_decision_actor__RAND__.value, t: 'meetings_decision_table', f: 'decision_actor' },
				success: function(resp) {
					$j('[id=decision_actor-container__RAND__], [id=decision_actor-container-readonly__RAND__]').html('<span class="match-text" id="decision_actor-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

					if(typeof(decision_actor_update_autofills__RAND__) == 'function') decision_actor_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/meetings_decision_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/meetings_decision_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#decision_description').replaceWith('<div class=\"form-control-static\" id=\"decision_description\">' + (\$j('#decision_description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#decision_actor').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#decision_actor_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#action_taken_with_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#action_taken_with_dateDay, #action_taken_with_dateMonth, #action_taken_with_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#decision_status').replaceWith('<div class=\"form-control-static\" id=\"decision_status\">' + (\$j('#decision_status').val() || '') + '</div>'); \$j('#decision_status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#decision_status_update_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#decision_status_update_dateDay, #decision_status_update_dateMonth, #decision_status_update_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#decision_status_remarks_by_superior').replaceWith('<div class=\"form-control-static\" id=\"decision_status_remarks_by_superior\">' + (\$j('#decision_status_remarks_by_superior').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(agenda_lookup)%%>', $combo_agenda_lookup->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(agenda_lookup)%%>', $combo_agenda_lookup->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(agenda_lookup)%%>', urlencode($combo_agenda_lookup->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(decision_actor)%%>', $combo_decision_actor->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(decision_actor)%%>', $combo_decision_actor->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(decision_actor)%%>', urlencode($combo_decision_actor->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(action_taken_with_date)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_action_taken_with_date->GetHTML(true) . '</div>' : 
			$combo_action_taken_with_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(action_taken_with_date)%%>', $combo_action_taken_with_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(decision_status)%%>', $combo_decision_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(decision_status)%%>', $combo_decision_status->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(decision_status_update_date)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_decision_status_update_date->GetHTML(true) . '</div>' : 
			$combo_decision_status_update_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(decision_status_update_date)%%>', $combo_decision_status_update_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['agenda_lookup' => ['meetings_agenda_table', 'Agenda of Meeting'], 'decision_actor' => ['user_table', 'Decision actor'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(agenda_lookup)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(decision_description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(decision_actor)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(action_taken_with_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(decision_status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(decision_status_update_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(decision_status_remarks_by_superior)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(meetings_decision_str)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tenant_id)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(agenda_lookup)%%>', safe_html($urow['agenda_lookup']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(agenda_lookup)%%>', urlencode($urow['agenda_lookup']), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_description)%%>', safe_html($urow['decision_description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_description)%%>', urlencode($urow['decision_description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(decision_actor)%%>', safe_html($urow['decision_actor']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(decision_actor)%%>', html_attr($row['decision_actor']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_actor)%%>', urlencode($urow['decision_actor']), $templateCode);
		$templateCode = str_replace('<%%VALUE(action_taken_with_date)%%>', app_datetime($row['action_taken_with_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(action_taken_with_date)%%>', urlencode(app_datetime($urow['action_taken_with_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(decision_status)%%>', safe_html($urow['decision_status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(decision_status)%%>', html_attr($row['decision_status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status)%%>', urlencode($urow['decision_status']), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_status_update_date)%%>', app_datetime($row['decision_status_update_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status_update_date)%%>', urlencode(app_datetime($urow['decision_status_update_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(decision_status_remarks_by_superior)%%>', safe_html($urow['decision_status_remarks_by_superior']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(decision_status_remarks_by_superior)%%>', html_attr($row['decision_status_remarks_by_superior']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status_remarks_by_superior)%%>', urlencode($urow['decision_status_remarks_by_superior']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(meetings_decision_str)%%>', safe_html($urow['meetings_decision_str']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(meetings_decision_str)%%>', urlencode($urow['meetings_decision_str']), $templateCode);
		$templateCode = str_replace('<%%VALUE(tenant_id)%%>', safe_html($urow['tenant_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tenant_id)%%>', urlencode($urow['tenant_id']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(agenda_lookup)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(agenda_lookup)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_actor)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_actor)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(action_taken_with_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(action_taken_with_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_status)%%>', 'Yet to Start', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status)%%>', urlencode('Yet to Start'), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_status_update_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status_update_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(decision_status_remarks_by_superior)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(decision_status_remarks_by_superior)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(meetings_decision_str)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(meetings_decision_str)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tenant_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tenant_id)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');
	if(isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>')
		$templateCode.="\n<input type=hidden name=agenda_lookup value=\"" . html_attr($filterValue[1]) . "\">\n";

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('meetings_decision_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('meetings_decision_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('meetings_decision_table');
		$rdata = $row;
	}
	$templateCode .= loadView('meetings_decision_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: meetings_decision_table_dv
	if(function_exists('meetings_decision_table_dv')) {
		$args = [];
		meetings_decision_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}