<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/suggestion.php');
	include_once(__DIR__ . '/suggestion_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('suggestion');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'suggestion';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`suggestion`.`id`" => "id",
		"`suggestion`.`suggestion`" => "suggestion",
		"`suggestion`.`attachment`" => "attachment",
		"`suggestion`.`created_by`" => "created_by",
		"`suggestion`.`created_at`" => "created_at",
		"`suggestion`.`last_updated_by`" => "last_updated_by",
		"`suggestion`.`last_updated_at`" => "last_updated_at",
		"`suggestion`.`tenant_id`" => "tenant_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`suggestion`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`suggestion`.`tenant_id`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`suggestion`.`id`" => "id",
		"`suggestion`.`suggestion`" => "suggestion",
		"`suggestion`.`attachment`" => "attachment",
		"`suggestion`.`created_by`" => "created_by",
		"`suggestion`.`created_at`" => "created_at",
		"`suggestion`.`last_updated_by`" => "last_updated_by",
		"`suggestion`.`last_updated_at`" => "last_updated_at",
		"`suggestion`.`tenant_id`" => "tenant_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`suggestion`.`id`" => "ID",
		"`suggestion`.`suggestion`" => "Suggestion",
		"`suggestion`.`attachment`" => "Attachment",
		"`suggestion`.`created_by`" => "Created By",
		"`suggestion`.`created_at`" => "Created At",
		"`suggestion`.`last_updated_by`" => "Last Updated By",
		"`suggestion`.`last_updated_at`" => "Last Updated At",
		"`suggestion`.`tenant_id`" => "Tenant ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`suggestion`.`id`" => "id",
		"`suggestion`.`suggestion`" => "suggestion",
		"`suggestion`.`attachment`" => "attachment",
		"`suggestion`.`created_by`" => "created_by",
		"`suggestion`.`created_at`" => "created_at",
		"`suggestion`.`last_updated_by`" => "last_updated_by",
		"`suggestion`.`last_updated_at`" => "last_updated_at",
		"`suggestion`.`tenant_id`" => "tenant_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`suggestion` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'suggestion_view.php';
	$x->TableTitle = 'Suggestions - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`suggestion`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Suggestion', 'Attachment', 'Created By', 'Created At', 'Last Updated By', 'Last Updated At', 'Tenant ID', ];
	$x->ColFieldName = ['id', 'suggestion', 'attachment', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', 'tenant_id', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/suggestion_templateTV.html';
	$x->SelectedTemplate = 'templates/suggestion_templateTVS.html';
	$x->TemplateDV = 'templates/suggestion_templateDV.html';
	$x->TemplateDVP = 'templates/suggestion_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: suggestion_init
	$render = true;
	if(function_exists('suggestion_init')) {
		$args = [];
		$render = suggestion_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: suggestion_header
	$headerCode = '';
	if(function_exists('suggestion_header')) {
		$args = [];
		$headerCode = suggestion_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: suggestion_footer
	$footerCode = '';
	if(function_exists('suggestion_footer')) {
		$args = [];
		$footerCode = suggestion_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
