<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/user_table.php');
	include_once(__DIR__ . '/user_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('user_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'user_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`user_table`.`id`" => "id",
		"`user_table`.`memberID`" => "memberID",
		"`user_table`.`name`" => "name",
		"`user_table`.`tenant_id`" => "tenant_id",
		"`user_table`.`created_by`" => "created_by",
		"`user_table`.`created_at`" => "created_at",
		"`user_table`.`last_updated_by`" => "last_updated_by",
		"`user_table`.`last_updated_at`" => "last_updated_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`user_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`user_table`.`tenant_id`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`user_table`.`id`" => "id",
		"`user_table`.`memberID`" => "memberID",
		"`user_table`.`name`" => "name",
		"`user_table`.`tenant_id`" => "tenant_id",
		"`user_table`.`created_by`" => "created_by",
		"`user_table`.`created_at`" => "created_at",
		"`user_table`.`last_updated_by`" => "last_updated_by",
		"`user_table`.`last_updated_at`" => "last_updated_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`user_table`.`id`" => "ID",
		"`user_table`.`memberID`" => "Member ID",
		"`user_table`.`name`" => "Name",
		"`user_table`.`tenant_id`" => "Tenant ID",
		"`user_table`.`created_by`" => "Created By",
		"`user_table`.`created_at`" => "Created At",
		"`user_table`.`last_updated_by`" => "Last Updated By",
		"`user_table`.`last_updated_at`" => "Last Updated At",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`user_table`.`id`" => "id",
		"`user_table`.`memberID`" => "memberID",
		"`user_table`.`name`" => "name",
		"`user_table`.`tenant_id`" => "tenant_id",
		"`user_table`.`created_by`" => "created_by",
		"`user_table`.`created_at`" => "created_at",
		"`user_table`.`last_updated_by`" => "last_updated_by",
		"`user_table`.`last_updated_at`" => "last_updated_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`user_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'user_table_view.php';
	$x->TableTitle = 'User Table';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`user_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Member ID', 'Name', 'Tenant ID', 'Created By', 'Created At', 'Last Updated By', 'Last Updated At', ];
	$x->ColFieldName = ['id', 'memberID', 'name', 'tenant_id', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/user_table_templateTV.html';
	$x->SelectedTemplate = 'templates/user_table_templateTVS.html';
	$x->TemplateDV = 'templates/user_table_templateDV.html';
	$x->TemplateDVP = 'templates/user_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: user_table_init
	$render = true;
	if(function_exists('user_table_init')) {
		$args = [];
		$render = user_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: user_table_header
	$headerCode = '';
	if(function_exists('user_table_header')) {
		$args = [];
		$headerCode = user_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: user_table_footer
	$footerCode = '';
	if(function_exists('user_table_footer')) {
		$args = [];
		$footerCode = user_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
