<?php

// Data functions (insert, update, delete, form) for table visiting_card_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function visiting_card_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('visiting_card_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'name' => Request::val('name', ''),
		'recommended_by' => Request::val('recommended_by', ''),
		'designation' => Request::val('designation', ''),
		'company_name' => Request::val('company_name', ''),
		'mobile_no' => Request::val('mobile_no', ''),
		'email' => Request::val('email', ''),
		'company_website_addr' => Request::val('company_website_addr', ''),
		'given_by' => Request::lookup('given_by', ''),
		'suggested_way_forward' => Request::val('suggested_way_forward', ''),
		'front_img' => Request::fileUpload('front_img', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'front_img', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'front_img', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('visiting_card_table', 'front_img', Request::val('SelectedID'));
			},
		]),
		'back_img' => Request::fileUpload('back_img', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'back_img', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'back_img', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('visiting_card_table', 'back_img', Request::val('SelectedID'));
			},
		]),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('visiting_card_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		visiting_card_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function visiting_card_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function visiting_card_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('visiting_card_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: visiting_card_table_before_delete
	if(function_exists('visiting_card_table_before_delete')) {
		$args = [];
		if(!visiting_card_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: meetings_table
	$res = sql("SELECT `id` FROM `visiting_card_table` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `meetings_table` WHERE `visiting_card_lookup`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="meetings_table_view.php?filterer_visiting_card_lookup=' . urlencode($id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'meetings_table'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'meetings_table'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `visiting_card_table_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `visiting_card_table_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `visiting_card_table` WHERE `id`='{$selected_id}'", $eo);

	// hook: visiting_card_table_after_delete
	if(function_exists('visiting_card_table_after_delete')) {
		$args = [];
		visiting_card_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='visiting_card_table' AND `pkValue`='{$selected_id}'", $eo);
}

function visiting_card_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('visiting_card_table', $selected_id, 'edit')) return false;

	$data = [
		'name' => Request::val('name', ''),
		'recommended_by' => Request::val('recommended_by', ''),
		'designation' => Request::val('designation', ''),
		'company_name' => Request::val('company_name', ''),
		'mobile_no' => Request::val('mobile_no', ''),
		'email' => Request::val('email', ''),
		'company_website_addr' => Request::val('company_website_addr', ''),
		'given_by' => Request::lookup('given_by', ''),
		'suggested_way_forward' => Request::val('suggested_way_forward', ''),
		'front_img' => Request::fileUpload('front_img', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'front_img', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'front_img', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('visiting_card_table', 'front_img', $selected_id);
			},
		]),
		'back_img' => Request::fileUpload('back_img', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'back_img', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('visiting_card_table', 'back_img', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('visiting_card_table', 'back_img', $selected_id);
			},
		]),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('visiting_card_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: visiting_card_table_before_update
	if(function_exists('visiting_card_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!visiting_card_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'visiting_card_table', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="visiting_card_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('visiting_card_table', $data['selectedID'], calculated_fields()['visiting_card_table']);

	// hook: visiting_card_table_after_update
	if(function_exists('visiting_card_table_after_update')) {
		if($row = getRecord('visiting_card_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!visiting_card_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('visiting_card_table', $selected_id);
}

function visiting_card_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('visiting_card_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('visiting_card_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('visiting_card_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('visiting_card_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_given_by = Request::val('filterer_given_by');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: recommended_by
	$combo_recommended_by = new Combo;
	$combo_recommended_by->ListType = 0;
	$combo_recommended_by->MultipleSeparator = ', ';
	$combo_recommended_by->ListBoxHeight = 10;
	$combo_recommended_by->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/visiting_card_table.recommended_by.csv')) {
		$recommended_by_data = addslashes(implode('', @file(__DIR__ . '/hooks/visiting_card_table.recommended_by.csv')));
		$combo_recommended_by->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($recommended_by_data))));
		$combo_recommended_by->ListData = $combo_recommended_by->ListItem;
	} else {
		$combo_recommended_by->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("CEO;;PD;;GM"))));
		$combo_recommended_by->ListData = $combo_recommended_by->ListItem;
	}
	$combo_recommended_by->SelectName = 'recommended_by';
	// combobox: given_by
	$combo_given_by = new DataCombo;
	// combobox: suggested_way_forward
	$combo_suggested_way_forward = new Combo;
	$combo_suggested_way_forward->ListType = 0;
	$combo_suggested_way_forward->MultipleSeparator = ', ';
	$combo_suggested_way_forward->ListBoxHeight = 10;
	$combo_suggested_way_forward->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/visiting_card_table.suggested_way_forward.csv')) {
		$suggested_way_forward_data = addslashes(implode('', @file(__DIR__ . '/hooks/visiting_card_table.suggested_way_forward.csv')));
		$combo_suggested_way_forward->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($suggested_way_forward_data))));
		$combo_suggested_way_forward->ListData = $combo_suggested_way_forward->ListItem;
	} else {
		$combo_suggested_way_forward->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("CEO;;PD;;GM"))));
		$combo_suggested_way_forward->ListData = $combo_suggested_way_forward->ListItem;
	}
	$combo_suggested_way_forward->SelectName = 'suggested_way_forward';

	if($hasSelectedId) {
		if(!($row = getRecord('visiting_card_table', $selectedId))) {
			return error_message($Translation['No records found'], 'visiting_card_table_view.php', false);
		}
		$combo_recommended_by->SelectedData = $row['recommended_by'];
		$combo_given_by->SelectedData = $row['given_by'];
		$combo_suggested_way_forward->SelectedData = $row['suggested_way_forward'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_recommended_by->SelectedText = (isset($filterField[1]) && $filterField[1] == '3' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_given_by->SelectedData = $filterer_given_by;
		$combo_suggested_way_forward->SelectedText = (isset($filterField[1]) && $filterField[1] == '10' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_recommended_by->Render();
	$combo_given_by->HTML = '<span id="given_by-container' . $rnd1 . '"></span><input type="hidden" name="given_by" id="given_by' . $rnd1 . '" value="' . html_attr($combo_given_by->SelectedData) . '">';
	$combo_given_by->MatchText = '<span id="given_by-container-readonly' . $rnd1 . '"></span><input type="hidden" name="given_by" id="given_by' . $rnd1 . '" value="' . html_attr($combo_given_by->SelectedData) . '">';
	$combo_suggested_way_forward->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_given_by__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['given_by'] : htmlspecialchars($filterer_given_by, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(given_by_reload__RAND__) == 'function') given_by_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function given_by_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#given_by-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_given_by__RAND__.value, t: 'visiting_card_table', f: 'given_by' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="given_by"]').val(resp.results[0].id);
							$j('[id=given_by-container-readonly__RAND__]').html('<span class="match-text" id="given_by-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


							if(typeof(given_by_update_autofills__RAND__) == 'function') given_by_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'visiting_card_table', f: 'given_by' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_given_by__RAND__.value = e.added.id;
				AppGini.current_given_by__RAND__.text = e.added.text;
				$j('[name="given_by"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


				if(typeof(given_by_update_autofills__RAND__) == 'function') given_by_update_autofills__RAND__();
			});

			if(!$j("#given_by-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_given_by__RAND__.value, t: 'visiting_card_table', f: 'given_by' },
					success: function(resp) {
						$j('[name="given_by"]').val(resp.results[0].id);
						$j('[id=given_by-container-readonly__RAND__]').html('<span class="match-text" id="given_by-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

						if(typeof(given_by_update_autofills__RAND__) == 'function') given_by_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_given_by__RAND__.value, t: 'visiting_card_table', f: 'given_by' },
				success: function(resp) {
					$j('[id=given_by-container__RAND__], [id=given_by-container-readonly__RAND__]').html('<span class="match-text" id="given_by-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

					if(typeof(given_by_update_autofills__RAND__) == 'function') given_by_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/visiting_card_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/visiting_card_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Visiting card table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (\$j('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#recommended_by').replaceWith('<div class=\"form-control-static\" id=\"recommended_by\">' + (\$j('#recommended_by').val() || '') + '</div>'); \$j('#recommended_by-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#designation').replaceWith('<div class=\"form-control-static\" id=\"designation\">' + (\$j('#designation').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#company_name').replaceWith('<div class=\"form-control-static\" id=\"company_name\">' + (\$j('#company_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#mobile_no').replaceWith('<div class=\"form-control-static\" id=\"mobile_no\">' + (\$j('#mobile_no').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#email').parent().replaceWith(`<div class=\"form-control-static\" id=\"email\">\${\$j('#email').val() || ''}\${\$j('#email').val() ? '<a target=\"_blank\" class=\"hspacer-lg\" href=\"mailto:' + \$j('#email').val() + '\" target=\"_blank\"><i class=\"glyphicon glyphicon-envelope\"></i></a>' : ''}</div>`);\n";
		$jsReadOnly .= "\t\$j('#company_website_addr').replaceWith('<div class=\"form-control-static\" id=\"company_website_addr\">' + (\$j('#company_website_addr').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#given_by').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#given_by_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#suggested_way_forward').replaceWith('<div class=\"form-control-static\" id=\"suggested_way_forward\">' + (\$j('#suggested_way_forward').val() || '') + '</div>'); \$j('#suggested_way_forward-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#front_img').replaceWith('<div class=\"form-control-static\" id=\"front_img\">' + (\$j('#front_img').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#back_img').replaceWith('<div class=\"form-control-static\" id=\"back_img\">' + (\$j('#back_img').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(recommended_by)%%>', $combo_recommended_by->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(recommended_by)%%>', $combo_recommended_by->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(given_by)%%>', $combo_given_by->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(given_by)%%>', $combo_given_by->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(given_by)%%>', urlencode($combo_given_by->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(suggested_way_forward)%%>', $combo_suggested_way_forward->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(suggested_way_forward)%%>', $combo_suggested_way_forward->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['given_by' => ['user_table', 'Given by'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(recommended_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(designation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(company_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mobile_no)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(company_website_addr)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(given_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(suggested_way_forward)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(front_img)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="front_img" id="front_img" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['front_img'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(front_img)%%>', '<input type="checkbox" name="front_img_remove" id="front_img_remove" value="1"> <label for="front_img_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(front_img)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(back_img)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="back_img" id="back_img" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['back_img'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(back_img)%%>', '<input type="checkbox" name="back_img_remove" id="back_img_remove" value="1"> <label for="back_img_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(back_img)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(visiting_card_str)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tenant_id)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(recommended_by)%%>', safe_html($urow['recommended_by']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(recommended_by)%%>', html_attr($row['recommended_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended_by)%%>', urlencode($urow['recommended_by']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(designation)%%>', safe_html($urow['designation']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(designation)%%>', html_attr($row['designation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(designation)%%>', urlencode($urow['designation']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(company_name)%%>', safe_html($urow['company_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(company_name)%%>', html_attr($row['company_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_name)%%>', urlencode($urow['company_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mobile_no)%%>', safe_html($urow['mobile_no']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mobile_no)%%>', html_attr($row['mobile_no']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mobile_no)%%>', urlencode($urow['mobile_no']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(company_website_addr)%%>', safe_html($urow['company_website_addr']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(company_website_addr)%%>', html_attr($row['company_website_addr']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_website_addr)%%>', urlencode($urow['company_website_addr']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(given_by)%%>', safe_html($urow['given_by']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(given_by)%%>', html_attr($row['given_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(given_by)%%>', urlencode($urow['given_by']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(suggested_way_forward)%%>', safe_html($urow['suggested_way_forward']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(suggested_way_forward)%%>', html_attr($row['suggested_way_forward']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(suggested_way_forward)%%>', urlencode($urow['suggested_way_forward']), $templateCode);
		$row['front_img'] = ($row['front_img'] != '' ? $row['front_img'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(front_img)%%>', safe_html($urow['front_img']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(front_img)%%>', html_attr($row['front_img']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(front_img)%%>', urlencode($urow['front_img']), $templateCode);
		$row['back_img'] = ($row['back_img'] != '' ? $row['back_img'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(back_img)%%>', safe_html($urow['back_img']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(back_img)%%>', html_attr($row['back_img']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(back_img)%%>', urlencode($urow['back_img']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(visiting_card_str)%%>', safe_html($urow['visiting_card_str']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(visiting_card_str)%%>', urlencode($urow['visiting_card_str']), $templateCode);
		$templateCode = str_replace('<%%VALUE(tenant_id)%%>', safe_html($urow['tenant_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tenant_id)%%>', urlencode($urow['tenant_id']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(recommended_by)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended_by)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(designation)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(designation)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(company_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mobile_no)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mobile_no)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(company_website_addr)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_website_addr)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(given_by)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(given_by)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(suggested_way_forward)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(suggested_way_forward)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(front_img)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(back_img)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(visiting_card_str)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(visiting_card_str)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tenant_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tenant_id)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('visiting_card_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('visiting_card_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('visiting_card_table');
		$rdata = $row;
	}
	$templateCode .= loadView('visiting_card_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: visiting_card_table_dv
	if(function_exists('visiting_card_table_dv')) {
		$args = [];
		visiting_card_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}