<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/visiting_card_table.php');
	include_once(__DIR__ . '/visiting_card_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('visiting_card_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'visiting_card_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`visiting_card_table`.`id`" => "id",
		"`visiting_card_table`.`name`" => "name",
		"`visiting_card_table`.`recommended_by`" => "recommended_by",
		"`visiting_card_table`.`designation`" => "designation",
		"`visiting_card_table`.`company_name`" => "company_name",
		"`visiting_card_table`.`mobile_no`" => "mobile_no",
		"`visiting_card_table`.`email`" => "email",
		"`visiting_card_table`.`company_website_addr`" => "company_website_addr",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Given by */" => "given_by",
		"`visiting_card_table`.`suggested_way_forward`" => "suggested_way_forward",
		"`visiting_card_table`.`front_img`" => "front_img",
		"`visiting_card_table`.`back_img`" => "back_img",
		"`visiting_card_table`.`created_by`" => "created_by",
		"`visiting_card_table`.`created_at`" => "created_at",
		"`visiting_card_table`.`last_updated_by`" => "last_updated_by",
		"`visiting_card_table`.`last_updated_at`" => "last_updated_at",
		"`visiting_card_table`.`visiting_card_str`" => "visiting_card_str",
		"`visiting_card_table`.`tenant_id`" => "tenant_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`visiting_card_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => '`visiting_card_table`.`tenant_id`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`visiting_card_table`.`id`" => "id",
		"`visiting_card_table`.`name`" => "name",
		"`visiting_card_table`.`recommended_by`" => "recommended_by",
		"`visiting_card_table`.`designation`" => "designation",
		"`visiting_card_table`.`company_name`" => "company_name",
		"`visiting_card_table`.`mobile_no`" => "mobile_no",
		"`visiting_card_table`.`email`" => "email",
		"`visiting_card_table`.`company_website_addr`" => "company_website_addr",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Given by */" => "given_by",
		"`visiting_card_table`.`suggested_way_forward`" => "suggested_way_forward",
		"`visiting_card_table`.`front_img`" => "front_img",
		"`visiting_card_table`.`back_img`" => "back_img",
		"`visiting_card_table`.`created_by`" => "created_by",
		"`visiting_card_table`.`created_at`" => "created_at",
		"`visiting_card_table`.`last_updated_by`" => "last_updated_by",
		"`visiting_card_table`.`last_updated_at`" => "last_updated_at",
		"`visiting_card_table`.`visiting_card_str`" => "visiting_card_str",
		"`visiting_card_table`.`tenant_id`" => "tenant_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`visiting_card_table`.`id`" => "ID",
		"`visiting_card_table`.`name`" => "Name",
		"`visiting_card_table`.`recommended_by`" => "Recommended by",
		"`visiting_card_table`.`designation`" => "Designation",
		"`visiting_card_table`.`company_name`" => "Company name",
		"`visiting_card_table`.`mobile_no`" => "Mobile no",
		"`visiting_card_table`.`email`" => "Email",
		"`visiting_card_table`.`company_website_addr`" => "Company website address",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Given by */" => "Given by",
		"`visiting_card_table`.`suggested_way_forward`" => "Suggested way forward",
		"`visiting_card_table`.`created_by`" => "Created by",
		"`visiting_card_table`.`created_at`" => "Created at",
		"`visiting_card_table`.`last_updated_by`" => "Last updated by",
		"`visiting_card_table`.`last_updated_at`" => "Last updated at",
		"`visiting_card_table`.`visiting_card_str`" => "Visiting card str",
		"`visiting_card_table`.`tenant_id`" => "Tenant ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`visiting_card_table`.`id`" => "id",
		"`visiting_card_table`.`name`" => "name",
		"`visiting_card_table`.`recommended_by`" => "recommended_by",
		"`visiting_card_table`.`designation`" => "designation",
		"`visiting_card_table`.`company_name`" => "company_name",
		"`visiting_card_table`.`mobile_no`" => "mobile_no",
		"`visiting_card_table`.`email`" => "email",
		"`visiting_card_table`.`company_website_addr`" => "company_website_addr",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Given by */" => "given_by",
		"`visiting_card_table`.`suggested_way_forward`" => "suggested_way_forward",
		"`visiting_card_table`.`created_by`" => "created_by",
		"`visiting_card_table`.`created_at`" => "created_at",
		"`visiting_card_table`.`last_updated_by`" => "last_updated_by",
		"`visiting_card_table`.`last_updated_at`" => "last_updated_at",
		"`visiting_card_table`.`visiting_card_str`" => "visiting_card_str",
		"`visiting_card_table`.`tenant_id`" => "tenant_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['given_by' => 'Given by', ];

	$x->QueryFrom = "`visiting_card_table` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`id`=`visiting_card_table`.`given_by` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'visiting_card_table_view.php';
	$x->TableTitle = 'Visiting card - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`visiting_card_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Name', 'Recommended by', 'Designation', 'Company name', 'Mobile no', 'Email', 'Company website address', 'Given by', 'Suggested way forward', 'Front img', 'Back img', 'Created by', 'Created at', 'Last updated by', 'Last updated at', 'Visiting card str', 'Tenant ID', ];
	$x->ColFieldName = ['id', 'name', 'recommended_by', 'designation', 'company_name', 'mobile_no', 'email', 'company_website_addr', 'given_by', 'suggested_way_forward', 'front_img', 'back_img', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', 'visiting_card_str', 'tenant_id', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/visiting_card_table_templateTV.html';
	$x->SelectedTemplate = 'templates/visiting_card_table_templateTVS.html';
	$x->TemplateDV = 'templates/visiting_card_table_templateDV.html';
	$x->TemplateDVP = 'templates/visiting_card_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: visiting_card_table_init
	$render = true;
	if(function_exists('visiting_card_table_init')) {
		$args = [];
		$render = visiting_card_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: visiting_card_table_header
	$headerCode = '';
	if(function_exists('visiting_card_table_header')) {
		$args = [];
		$headerCode = visiting_card_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: visiting_card_table_footer
	$footerCode = '';
	if(function_exists('visiting_card_table_footer')) {
		$args = [];
		$footerCode = visiting_card_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
